### ISSUE TITLE
Fix Remove file/link button

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#102]
On the patch edit page the Remove buttons are not functional if there is only one link or file.
Either the button should be hidden if there is only one item in the list, or (preferred) it should reset the content of the item (delete) when pressed.
Even better if it is hidden when there's no value, so nothing to remove.

To see the current behaviour, create a new patch, upload a file, then press REMOVE. Currently it does nothing, unless you upload or link more than one file in which case it works just the way it should.

**Comment by goozo** [comment]
closing as I think this is fixed.
