### ISSUE TITLE
Safari CSS warnings

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#119]
[Warning] Unexpected CSS token: : (app-style.css, line 392)
[Warning] Unexpected CSS token: : (app-style.css, line 403)
[Warning] Unexpected CSS token: : (app-style.css, line 494)
[Warning] Unexpected CSS token: : (app-style.css, line 520)

e.g.
```
.patch-tile-new {
    -moz-opacity: 0.50;
    -khtml-opacity: 0.50;
    opacity: 0.50;
    -ms-filter:"progid:DXImageTransform.Microsoft.Alpha"(Opacity=50);
    filter: progid:DXImageTransform.Microsoft.Alpha(opacity=50);
    filter:alpha(opacity=50);
    cursor: pointer;
}
```
progid: value should be quoted
Probably there shouldn't be two filter entries either.

**Comment by goozo** [comment]
done.
