### ISSUE TITLE
Remove CPU and memory details

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#121]
CPU and memory usage should not be in the patch details form.
Also the information should not be shown in the patch details.

The data is frequently wrong and changes as we make the firmware more efficient. As long as the load is less than 100% the details aren't important.

In the future we might add some automatic benchmarking instead. When a user loads a patch over Web MIDI, the cpu and memory load can be determined in real time. This could be used to mark a patch as working or failed (over memory / over CPU / load error / compile error).

The read-out from a connected device should remain.

**Comment by goozo** [comment]
this should now be in dev.
