### ISSUE TITLE
SPA staging issues

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#122]
It's awesome! Some minor issues to fix:

1.  Patch Compiltation Failed / Succeeded typo (Compilation)
2. Missing patch detail items in medium and small size responsive display (zoom in to see):
  - Channels, CPU, Memory, Download link, tags (compare live site)
3. Parameter names should be visible when knobs are disabled
4. Change buttons to: `TEST` `LOAD` `COMPILE`
5. Remove `Compile Patch` link from lhs pane (`BUILD: Compile Patch` above tags)
6. Remove placeholder messages (OwlControl / Connection Status: ...)

**Comment by goozo** [comment]
1. Fixed
2. yep, on the list
3. They are currently visible (should perhaps make darker grey though if hard to see.)
4. `COMPILE` yep makes sense,`TEST` and`LOAD` I would argue as a newbie are not obvious what they mean / do,  suggest:  `TEST IN BROWSER` , `LOAD TO OWL` , otherwise a user might think `load` in browser and `test` on owl.
5. ok
6. yep placeholders will come off once owl command has been integrated.

**Comment by goozo** [comment]
Fixed an issue where refreshing a spa deep link page caused the spa not to load. (fixed in dev)

**Comment by pingdynasty** [comment]
TEST / LOAD: yes they're not great labels. I've been trying to come up with smth better ( PLAY / UPLOAD / SEND ...) but I think the problem is that these are unusual things to do in a browser and there's not an established convention.

What do you think about having a help message on the page that says what the key functions are and how you use them - and why some things may be disabled. The user would only have to close it once, then the action would be remembered and the help screen not show again - or available with a ? icon.

My feeling is that we're fighting a loosing battle trying to make an intuitive, self-explanatory interface when for many users some of the actions are not intuitive at all.

Actually I think I prefer PLAY to TEST: after all, that's what we want to encourage people to do.

**Comment by pingdynasty** [comment]
done!
