### ISSUE TITLE
On screen keyboard as sound source in the patch-library

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlServer#129]
Sometimes a high-latency/jittery screen-based keyboard (with keybindings for the computer keyboard) is better than a loop playback of a file ...
does not have to be fully-featured, just a couple of sounds (piano, synth) :)

Alternatively, should only work as a MIDI controller for the running patch.

And of course, this keyboard should also be triggered by whatever MIDI device you have connected to your computer .

**Comment by pingdynasty** [comment]
I think we can split this into several parts:
1) add an optional 2-octave keyboard widget to the Play Patch section. Click a button / keyboard icon to make visible.
2) connect MIDI events from keyboard to patch.
3) generate sound and feed into patch.
4) keyboard shortcuts mapped to MIDI keys.
5) support external MIDI device.

Achieving 1) and 2) would already be awesome for playing / testing MIDI-enabled patches. 3) adds a lot of value, 4) and 5) are nice-to-haves.

**Comment by pingdynasty** [comment]
Superceded by #256 and #257
