### ISSUE TITLE
Create Patch form file upload to wrong directory

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#135]
The new Create Patch form seems to upload files to a temporary directory in the uploads folder.
The patch builder expects to find the files in a folder containing the patch id.

Either 
 1) the build script is updated to look in the right place, or
 2) the patch create process changed to generate an ID when the form is loaded, so that the files can be uploaded directly to the correct folder, or
 3) the files copied to the correct folder when the patch form is submitted.

**Comment by goozo** [comment]
fixed
