### ISSUE TITLE
Hide file path when creating or editing patch

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#161]
Currently the patch Create and Edit forms show the full URL for added files as an editable text.
This should be non-editable, with only the filename, and a link to open the target in a different window.

Nice to have: different colours or icons for Github and locally uploaded files.

**Comment by goozo** [comment]
added this for create form, icons not implemented yet but can do.  what would you like to use as icons?

**Comment by pingdynasty** [comment]
Pls find a generic file icon to use for all types.
