### ISSUE TITLE
Patch requires reload after compilation

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#167]
After editing a file and clicking Save & Compile, the Play button starts the previous version of the patch.
To reproduce, log in as test/test on staging and go to
https://staging.hoxtonowl.com/patch-library/patch/Test_Tone
Edit the file, change frequency range from `* 4000` to `* 400`.
Save & Compile, then Play: turning A still gives a range from 0 to 4kHz.

**Comment by goozo** [comment]
@pingdynasty this should be fixed.

**Comment by pingdynasty** [comment]
okay I've merged branch issue167_patchReloadAfterCompilation into master, closing this.
