### ISSUE TITLE
Edit Patch Description

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#168]
On the Patch Details page, the Description field should have an edit button if the current user is logged in and owns the patch (or is an admin).
The edit button should make the Description editable. When the user clicks the button (or changes the text) the edit button should be replaced by a save button.
Saving should update the database with the new description.

**Comment by samuele-artuso** [comment]
I guess you closed this because is a subset of #172?

**Comment by pingdynasty** [comment]
@goozo will take up @kYuZz branch and add the back end. This will form a reference for completing #172.

**Comment by goozo** [comment]
done
