### ISSUE TITLE
Create new patch page: unable to add source file from GitHub

### ISSUE THREAD

**Issue by samuele-artuso** [pingdynasty/OwlServer#195]
How to reproduce:
1. Go to "My patches"
1. Click "Create patch"
1. Paste this URL in the "GitHub File Url" input box: https://github.com/pingdynasty/OwlPatches/blob/master/FreeVerbPatch.hpp
1. Click "Save"
1. A new patch without a source file is created.

I believe this is a bug with the frontend because the URL of the source file is not sent along with the payload of the `POST /patches` API call:

![image](https://cloud.githubusercontent.com/assets/3853889/22383189/9dba344a-e4c0-11e6-8179-6b16ba29d102.png)

Sorry if this was already known or if for some reason is not an issue.

**Comment by samuele-artuso** [comment]
This is now in the staging environment.
* [Updated API documentation](https://github.com/pingdynasty/OwlServer/blob/dev/web/api/README.md)
* [Working example written in JavaScript](https://github.com/pingdynasty/OwlServer/blob/dev/web/api/examples/jwt-auth/index.js)
* [Fully fledged patch example]()

Bug reports are welcome.

**Comment by goozo** [comment]
it works for me, did you click the `add` button after pasting the github url? which browser and version can you reproduce this in?
