### ISSUE TITLE
Scroll bar not appearing

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#210]
not sure if this is an issue with my Windows 10 laptop or with the website but this page:
https://hoxtonowl.com/forums/topic/owl-control/
does not have any scroll bars in Chrome, Edge or FireFox

**Comment by goozo** [comment]
BBpress looks like it adds globally scoped css classes to the body depending on forum thread title. I added a fix to remove this current clash.

**Comment by goozo** [comment]
fixed.
