### ISSUE TITLE
SysEx download fails if not logged in

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#221]
Fails with a 401 if the user is not logged in. Presumably this has smth to do with the download count.

**Comment by pingdynasty** [comment]
This also affects Patch Load and Play.

**Comment by goozo** [comment]
when you say Load and Play do you mean on the owl? I was able to play https://hoxtonowl.com/patch-library/patch/Gain  in the browser ok

**Comment by pingdynasty** [comment]
If I log out and hit Play on the Gain patch I get a 401 (in the console) on:
`
getScript.js:18 GET https://hoxtonowl.com/api/builds/55074dcda82f90176ffe3bdc?format=js&download=0&cachebust=1507916715577 `

**Comment by pingdynasty** [comment]
.. which comes back with:
`{"status":401,"success":false,"message":"Not authorized."}`

**Comment by pingdynasty** [comment]
actually hitting the URL with curl from my local machine returns the patch...
It's fake bugs! Only seems to happen with an old version of Chrome on my Debian box.

**Comment by goozo** [comment]
seems to work.
