### ISSUE TITLE
Publish patch fails when fields missing

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#235]
To reproduce, create a new patch with empty `Description` and `Instructions`.
Press the Private padlock to publish.
Choosing `Yes` to publish then brings up an error message:
```
Unexpected token I in JSON at position 0
```
The server error log shows:
Error: Field 'description' is required.
Error: Field 'instructions' is required.

The user should be told what field/s are missing or invalid instead of getting a cryptic error message.

**Comment by f-rebeltech** [comment]
super stale
