### ISSUE TITLE
Update database with parameter meta data

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#241]
Currently parameter names are stored in key value pairs.
The parameter meta data we want is:
- parameter id (numeric)
- name
- io: input or output
- type: float (for knobs and cv's) or bool (for buttons and triggers)

Current patch parameters should all be converted to io: input and type: float.
Parameter id's should be assigned : a = 0, b = 1, ... e = 4.

**Comment by pingdynasty** [comment]
Buttons should have parameter id 80 to 87 and names `BUTTON_A` to `BUTTON_H`.

**Comment by goozo** [comment]
done on dev
