### ISSUE TITLE
Device Page: Don't refresh all information when patch loaded

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#267]
Currently on the Device Page, when selecting a new patch, some device information disappears: `STORAGE: N KB / M MB` 

There are different stats, pertaining to the patch:
LOADED PATCH: StereoFilterDelay
CPU: 64%
MEMORY: 625.01KB
plus program message and error

and the device:
FIRMWARE: OWL Pedal mkII v22.2.0
STORAGE: 208.75KB / 8MB
DEVICE UUID: 0044003e:32355104:32393433

Only the patch stats should be refreshed when a patch is loaded, ie PC message received.

Additionally, ideally only the Device Page should show the STORAGE and UUID.

**Comment by f-rebeltech** [comment]
fixed in 4fafc58

**Comment by f-rebeltech** [comment]
opened #270 to wrap this up
