### ISSUE TITLE
Add play button to patches

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#29]
Jonny's original design of the Patches has a Play button to listen to a sample:
http://hoxtonowl.com/wp-content/uploads/OwlServer/client/patches.html

If the patch has a soundcloud sample, this should be enabled.
However, to play from soundcloud we need to use the soundcloud player widget, which doesn't fit in the design.

Is it possible to have a single widget on the page (e.g. bottom-right corner, like on the Soundcloud website), remote-controlled with our own play buttons?

Soundcloud also offer a Mini Player to Pro users, which might be more suitable.
http://help.soundcloud.com/customer/portal/articles/1428418-what-are-the-differences-between-the-embeddable-players-

**Comment by samuele-artuso** [comment]
I've just bumped into [this](http://eventbox.fm/venue/the-shacklewell-arms?utm_source=venue&utm_medium=referral). Apparently they are playing streams from Soundcloud without a player... I have no idea about how they managed to do that, but will look into it.

**Comment by marsus** [comment]
low priority
