### ISSUE TITLE
Design Patch Edit page

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#30]
We need a simple design to create/edit patches.

Text fields:
* Name
* Description
* Instructions
* Parameter A/B/C/D/E name

Number fields:
* CPU cycles
* Memory bytes

Select:
* Inputs and Outputs: 0/1/2

Multiple selection:
* Tags

And links to add/remove:
* Samples (soundcloud links)
* Files (github links)

Adding samples and files could be done with a little pop-up that lets you paste in a link.

**Comment by samuele-artuso** [comment]
Am I safe to assume that:

* Any logged-in user is allowed to create new patches;
* Any logged-in user is allowed to edit only his/her own patches;
* author == name of Wordpress user.

**Comment by GuillaumeLeNost** [comment]
Seems fine to me

**Comment by samuele-artuso** [comment]
Which fields are mandatory?

**Comment by GuillaumeLeNost** [comment]
All mandatory except : Tags, Samples, Files.

**Comment by pingdynasty** [comment]
I think the parameter names must be optional, since not all patches use
all parameters.

Martin

On 11/02/15 14:59, GuillaumeLeNost wrote:
> All mandatory except : Tags, Samples, Files.
>
>
> > Le 11 févr. 2015 à 14:58, Sam Artuso <notifications@github.com> a
> écrit :
> >
> > Which fields are mandatory?
> >
> > —
> > Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/30#issuecomment-73894206>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/30#issuecomment-73894497>.
>

-- 
Martin Klang
Alpha Plus Technology Ltd
London UK

**Comment by samuele-artuso** [comment]
Here's the design http://staging.hoxtonowl.com/add-patch/

Feedback is welcome before I start working on making it functional.

**Comment by pingdynasty** [comment]
I like it! The tag selector is nice.

Can we make Parameter A optional as well (we've got one patch with no
parameters...)

And CPU cycles and Memory bytes optional too, pls.

And change 'Samples' to 'Soundcloud Samples'.

Good work.

Martin

**Comment by GuillaumeLeNost** [comment]
I like it as well !

Guillaume

**Comment by samuele-artuso** [comment]
does the GitHub section make more sense like in this?
![gh](https://cloud.githubusercontent.com/assets/3853889/6172110/bb41014c-b2d6-11e4-9ef3-6d74552c39fc.png)

**Comment by pingdynasty** [comment]
I think it will be easier all around if each file is a full github url, e.g.

https://github.com/pingdynasty/OwlPatches/blob/master/MoogPatch.hpp

We then need to extract the repository name, user and branch from that
URL to retrieve the file through a JSONP call.

Martin

**Comment by samuele-artuso** [comment]
All files must be in the same repo, right?

**Comment by GuillaumeLeNost** [comment]
Makes sense to me
Guillaume


Guillaume

**Comment by pingdynasty** [comment]
no, why?
You might use e.g. CircularBuffer.hpp from OwlPatches and your own patch
file.

On 12/02/15 18:12, GuillaumeLeNost wrote:
> Makes sense to me
> Guillaume
>
>
> Guillaume
>
> > On 12 févr. 2015, at 18:06, Sam Artuso <notifications@github.com> wrote:
> >
> > All files must be in the same repo, right?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/30#issuecomment-74121426>.
>

-- 
Martin Klang
Alpha Plus Technology Ltd
London UK
