### ISSUE TITLE
Wiki images missing

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#38]
We seem to have lost wiki media attachments, e.g. the images on
http://hoxtonowl.com/wiki/Getting_Started
and  http://hoxtonowl.com/wiki/Hardware_DFU

The attachment page (e.g. http://hoxtonowl.com/wiki/File:OwlFacePic.jpg ) says:
Error creating thumbnail: File seems to be missing:

The full size url resolves to a 404:
http://hoxtonowl.com/mediawiki/images/e/ed/OwlFacePic.jpg

**Comment by GuillaumeLeNost** [comment]
missing again!

**Comment by samuele-artuso** [comment]
Recovered [all images](http://hoxtonowl.com/mediawiki/index.php?title=Special%3AListFiles&limit=500&ilsearch=&user=) from a backup I had made.

The directory `wordpress/mediawiki/images` (where all wiki images get saved) is [not under version control](https://github.com/pingdynasty/OwlWeb/blob/master/.gitignore#L26), so I've added a line to the back-up script `owl.wp.backup.sh` for this not to happen again.
