### ISSUE TITLE
Search input box not visible

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#40]
The forum search function has a text input next to the SEARCH submit button, e.g. here:
http://hoxtonowl.com/forums/

On chrome and firefox the search box is not visible until you click on it to make it active.

Other text boxes such as lost password / register user are fine.

**Comment by samuele-artuso** [comment]
Works for me.

Checked on:
* Firefox 33 and Chrome 37 on Ubuntu 14.04;
* Internet Explorer 11, Firefox 34 and Chrome 39 on Windows 7 Enterprise.

Are you on OS X?

**Comment by GuillaumeLeNost** [comment]
I confirm the box is not visible on OSX.10.1, Chrome.

**Comment by samuele-artuso** [comment]
Guys, can you check if this is fixed? (don't forget to hard-refresh)

**Comment by GuillaumeLeNost** [comment]
Still invisible on Mac OS X with Chrome.
