### ISSUE TITLE
Enable browser history for patch browsing

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#41]
At the moment, in the patch library, clicking on a patch updates the current page. Clicking 'back' then takes the user to the previous page.
I think it would be better to consider Patch Details a different page (from the point of view of the user).

This applies to all or some of
- browser history
- breadcrumb
- page title

Whether Patch Details is implemented as a separate page or dynamically in one page is not important (to me!) but it would be good to have the ability to link directly to a specific patch page. The stripped.html page did this with the patch name as parameter, e.g. ?patch=Reverse%20Reverb

**Comment by samuele-artuso** [comment]
This is now fixed. It works, but it's far from perfect. A proper solution to this entails a bit of work. From a user standpoint, I think that there are many other "click" actions that should push a new item in the browser history.

Anyway:
* each patch can now be linked and bookmarked;
* the URL for each patch is easily readable;
* window title and breadcrumbs are updated accordingly.

Please let me know if you want me to work further on this.
