### ISSUE TITLE
Admin Delete Any Patch

### ISSUE THREAD

**Issue by GuillaumeLeNost** [pingdynasty/OwlServer#48]
when logged in as admin, display a "delete" button for any Patch.

**Comment by GuillaumeLeNost** [comment]
Can I test that already on the staging server ? don't see the edit button right now but I might be too impatient :)

**Comment by samuele-artuso** [comment]
Yes, it's already on the staging server.

There are two edit buttons.

The first one is in the patch detail page and it will enable you to edit any page. If you can't spot it, then you're either logged out, or you're not an administrator.

![screenshot1](https://cloud.githubusercontent.com/assets/3853889/6608883/15ac2cfc-c843-11e4-8e1b-745ddb4864d1.png)

The second pair is in the "My Patches" page. This enables users to edit their own patches. If you can't see it, you're probably not logged in.

![screenshot2](https://cloud.githubusercontent.com/assets/3853889/6608915/5f29c5ba-c843-11e4-9d7f-1493e3881f70.png)

**Comment by samuele-artuso** [comment]
You weren't an admin. I've just made user `giom` an administrator. Remember to log out and then back in, impatient boy!

**Comment by GuillaumeLeNost** [comment]
Cool ! Working now.
Thanks :)

**Comment by samuele-artuso** [comment]
If you find any bugs (and I bet you will), I'd appreciate if you gave me as much information as possible about the circumstances in which it occurred, including:
* browser used
* screenshot of the patch form
* description of what you were trying to do
* time, if possible - it would help spot problems in the logs

Cheers!
