### ISSUE TITLE
List of patch authors

### ISSUE THREAD

**Issue by samuele-artuso** [pingdynasty/OwlServer#50]
Please provide a list of WordPress usernames of patch authors.

Below is a comprehensive list of patch authors in the DB:

Albert Graef
brumme
Blondinou
Charles Verron
Christine Caulfield
Dave Moffat
Giulio Moro
Grame
Guitarix Development Team
Harry Haaren
Jag
Jason Frank
Johan Larsby
Julius O. Smith III
Marek Bereza
Martin Dittus
OWL
Oli Larkin
R Bristow-Johnson
Ross Bencina
Ryan Sarver
Yann Orlarey

**Comment by GuillaumeLeNost** [comment]
Patch Authors wordpress logins added after the dash when known:

Albert Graef
brumme
Blondinou - blondinou
Charles Verron
Christine Caulfield - chrissie
Dave Moffat
Giulio Moro
Grame
Guitarix Development Team
Harry Haaren
Jag
Jason Frank
Johan Larsby
Julius O. Smith III
Marek Bereza
Martin Dittus - martind2
OWL 
Oli Larkin - hibrasil
R Bristow-Johnson 
Ross Bencina
Ryan Sarver
Yann Orlarey

**Comment by samuele-artuso** [comment]
Integrated in the DB. You'll be able to assign other forum users to patches when #54 is closed.
