### ISSUE TITLE
List of admins

### ISSUE THREAD

**Issue by samuele-artuso** [pingdynasty/OwlServer#51]
Please provide a ilst of WordPress usernames that will be able to edit and delete any patches.

**Comment by GuillaumeLeNost** [comment]
List of admins:
giom
mars
tom

**Comment by samuele-artuso** [comment]
All those who are admins on the website will be automatically recognized as able to edit any patch or delete patches.

**Comment by pingdynasty** [comment]
awesome

On 05/03/15 19:10, Sam Artuso wrote:
>
> All those who are admins on the website will be automatically
> recognized as able to edit any patch or delete patches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/51#issuecomment-77430029>.
>

-- 
Martin Klang
Alpha Plus Technology Ltd
London UK
