### ISSUE TITLE
Migrate live server to nestor

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#52]
the live server is currently buenaventura.pingdynasty.com,
this should be migrated to nestor.pingdynasty.com at 46.226.111.228

**Comment by samuele-artuso** [comment]
* Backups set up.
* Postfix set up.

We can go live on Monday if that's fine with you.

**Comment by pingdynasty** [comment]
the sooner the better!

**Comment by samuele-artuso** [comment]
Migration completed successfully. Do you copy, Houston?

**Comment by GuillaumeLeNost** [comment]
yep, looks good except that the source code dos not display for a lot of patches.

**Comment by pingdynasty** [comment]
Which ones? Oli's?

Martin

On 17/03/15 12:14, GuillaumeLeNost wrote:
> yep, looks good except that the source code dos not display for a lot
> of patches.
>
>
> > Le 17 mars 2015 à 12:05, Sam Artuso <notifications@github.com> a écrit :
> >
> > Migration completed successfully. Do you copy, Houston?
> >
> > —
> > Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/52#issuecomment-82309260>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/52#issuecomment-82314759>.
>

-- 
Martin Klang
Alpha Plus Technology Ltd
London UK

**Comment by pingdynasty** [comment]
seems to be a problem with how the data is imported from the spreadsheet

e.g. Leaky Integrator has this github link
https://github.com/undefined/blob/master/https://github.com/pingdynasty/OwlPatches/blob/master/LeakyIntegratorPatch.hpp

In the spreadsheet, it has
Repo: pingdynasty/OwlPatches
Github: LeakyIntegratorPatch.hpp

I'll raise an issue.

Martin

On 17/03/15 12:14, GuillaumeLeNost wrote:
> yep, looks good except that the source code dos not display for a lot
> of patches.
>
>
> > Le 17 mars 2015 à 12:05, Sam Artuso <notifications@github.com> a écrit :
> >
> > Migration completed successfully. Do you copy, Houston?
> >
> > —
> > Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/52#issuecomment-82309260>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/52#issuecomment-82314759>.
>

-- 
Martin Klang
Alpha Plus Technology Ltd
London UK

**Comment by pingdynasty** [comment]
We're live! Closing.
