### ISSUE TITLE
Admin patch edit resets author field

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#54]
An admin user can edit any patch, not just the ones they own / authored.
When saving a patch owned by another user, the author field is set to be the admin user. This means that admin users can't manage other ppls patches, which is smth we require.

Ideal solution:
For admin users, the patch details page should include the author name, pre-populated with the current value (ie not reset to the admin users name).
This will also allow us to assign patches to existing users.

**Comment by samuele-artuso** [comment]
The pictures below show the way it's going to work. Hope to have it fully functional on Monday evening
![patch1](https://cloud.githubusercontent.com/assets/3853889/6534741/b2ff9e04-c437-11e4-9729-e5f09f5c30ad.png)
![patch2](https://cloud.githubusercontent.com/assets/3853889/6534742/b33d760c-c437-11e4-8ade-f00b48e5fd46.png)
![patch3](https://cloud.githubusercontent.com/assets/3853889/6534743/b3410984-c437-11e4-9ce4-51836b6776f3.png)


.

**Comment by pingdynasty** [comment]
looks good to me

**Comment by pingdynasty** [comment]
A simpler solution with just a text field is also acceptable. The name would have to match a wordpress username to allow that user to edit the patch later on.

**Comment by GuillaumeLeNost** [comment]
Yep, agreed.

Guillaume

**Comment by samuele-artuso** [comment]
Erm... I've just finished the front-end bit and this is the way it will look. In terms of time taken, it doesn't really make a big difference even if maybe it looks a bit of a fancy UI.

The tricky bit was associating patch authors with their internal WordPress user IDs, which is a piece of work needed either way.

**Comment by pingdynasty** [comment]
alright cool - bells and whistles it is then!
