### ISSUE TITLE
Add Latest Patches button

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#56]
It would be nice to be able to sort them by date created (descending).
We've got a Latest button in the design:
https://rawgit.com/pingdynasty/OwlServer/master/client/patches.html

I think it'd be cool if it just showed the same results as the default view (Browse All) but sorted by creation date instead of name.

**Comment by samuele-artuso** [comment]
The filter will be invisible when the "Latest" button is selected, won't it?

**Comment by pingdynasty** [comment]
yes I think that's the best way to do it.

Martin

**Comment by samuele-artuso** [comment]
as an admin, do you need to be able to edit the creation time?

**Comment by pingdynasty** [comment]
yes that would be nice
