### ISSUE TITLE
'Enveloppe' tag should be 'Envelope'

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#57]
Not sure where this is changed; database?

**Comment by pingdynasty** [comment]
btw this is low priority and should probably be done on the live website once we're live on nestor!

**Comment by GuillaumeLeNost** [comment]
nestor ??

i like :)

**Comment by pingdynasty** [comment]
yes, nestor makhno, the new live server -
taking over from buenaventura durruti

it's all looking good to me, are we ready to go live?

**Comment by samuele-artuso** [comment]
I think these are the most important points before going live:
* I'll set up automatic back-ups of files, MySQL and Mongo. Ideally the backups should be pulled down periodically and stored on another box;
* DNS - can you lower the TTL of the A record to something short like 5 minutes? this will help make sure that new posts on the forum don't get lost during the DB sync.
* Mongo - what is the best place where to sync patches from? the spreadsheet or the staging website?
* sendmail - do you have an SMTP server available for WordPress on nestor to send emails (registration, lost passwords and all that jazz).

**Comment by pingdynasty** [comment]
* mongo: sync from spreadsheet
* sendmail: can you set one up pls? postfix with no relay
* DNS - I'll do that right now

**Comment by pingdynasty** [comment]
* dns: done
* backups: once live I'll move the backup drive from buenaventura to nestor

**Comment by pingdynasty** [comment]
just thought of smth obvious and changed Enveloppe to Envelope in the spreadsheet...

**Comment by samuele-artuso** [comment]
ok, this will be automatically fixed on go live then (#52).
