### ISSUE TITLE
Log out not working

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#58]
The log out links don't work on staging, Chrome / Linux.

Same for both the new Log out in the menu bar and the Log out in the rh sidebar on the forum.

It goes to a plain html page [1] that says:
You are attempting to log out of The OWL
Do you really want to log out?

[1] http://staging.hoxtonowl.com/wp-login.php?action=logout

**Comment by samuele-artuso** [comment]
Strange. It works for me. Sure it is not a caching issue?

**Comment by pingdynasty** [comment]
you're probably right, works fine now.

**Comment by samuele-artuso** [comment]
or you must've experienced the issue before I hit cleared the APC cache.
