### ISSUE TITLE
Add published / unpublished field to patch

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#63]
It would be useful to let our users create patches without them being public.

I think that when a patch is created it should be private by default.
In My Patches there should then be an icon for each patch (along with edit and delete): publish / unpublish (or make public / make private).

Alternatively, add a field to the edit page: public / private. The My Patches list should clearly display which patches are private.

**Comment by samuele-artuso** [comment]
as an admin, would you rather be able to see or not to see user's private patches?

**Comment by pingdynasty** [comment]
good question - I can't see any reason to access other users' private
patches, so no.
But an admin user might have their own private patches which should be
visible in My Patches!

Martin

**Comment by samuele-artuso** [comment]
Fix staged.

**Comment by pingdynasty** [comment]
works well, it's good that private patches show up only in My Patches

**Comment by samuele-artuso** [comment]
This is now live.

**Comment by GuillaumeLeNost** [comment]
logged in or logged out, I don’t see any patches in the patches page !

**Comment by samuele-artuso** [comment]
Sorry, my blunder! It's fixed now.
