### ISSUE TITLE
Perform online compilation

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#66]
The user should be able to perform a build to generate a sysex file from the source files associated with a patch.

Steps involved:
* create temporary build directory
* download source files from github
* copy Makefile into build dir
* generate include file with patch name and filename details (note 1)
* run make command (progress bar not essential but nice to have)
* show error messages
* or: show success message and link patch to generated sysex file (downloadable)
* delete temporary directory

note 1: this might not be necessary if we pass all details to the build on the command line in the next stage

So a patch can have a sysex file associated with it. It would be a good idea to store the sysex file size and compilation date/time along with the filename.

I think that only the patch owner and admins should be able to compile, since it amounts to editing the patch details.

**Comment by samuele-artuso** [comment]
Can you show me how to compile one of the patches in a step-by-step fashion?

It'd be great if you could write the makefile — I have no idea how to do it, since I come from the much more hassle-free world of interpreted languages.

I think that for security reasons we should compile patches inside a virtual machine. I can easily set up one with Vagrant in a matter of minutes, if you agree with this approach. Ideally the step-by-step guide should include the tools and header libraries I need to install on a freshly installed Debian in order to be able to compile any patch written in any language.

**Comment by pingdynasty** [comment]
Yes pls go ahead and set up a virtual machine.
I'll write the makefile and give you a zip file with all required tools
and libraries. It's quite self-contained.

**Comment by pingdynasty** [comment]
I've uploaded a tgz to my account on nestor: OwlProgram.online.tgz
You can unzip it somewhere then run the make as follows:
* create an empty directory e.g. /tmp/foo
* copy patch file e.g. PhaserPatch.hpp to /tmp/foo
* cd to OwlProgram.online
* compile with
```make BUILD=/tmp/foo ONLINE_INCLUDES='#include \"PhaserPatch.hpp\"' ONLINE_REGISTER='REGISTER_PATCH(PhaserPatch, \"Phaser\", 2, 2);' online```
* if successful, move the file /tmp/foo/online.syx to its download location and delete tmp directory

In the make command, the relevant data is passed in the environment variables.
BUILD: absolute path of the build directory
ONLINE_INLCUDES: list of #includes, gets copied into the file online.h
ONLINE_REGISTER: contains the REGISTER_PATCH command.
This has the form REGISTER_PATCH(patchclass, patchname, inputchannels, outputchannels)

To quote the string literals (file includes and patchname) it is necessary to escape the quotes with backslashes.

You can see if there is a problem by looking in the tmp directory for the files online.h and online.cpp.

If it is easier for you to generate the temporary files (online.h and online.cpp) yourself then that is also possible. In this case, generate two files in the same way but called solopatch.h and solopatch.cpp, and execute the make command with `make BUILD=/tmp/foo solo`. The output file will be `solo.syx`.

**Comment by pingdynasty** [comment]
The build currently fails on nestor because the tools are compiled for 32-bit Linux. If you can run a 32bit VM that shouldn't be a problem.
Otherwise you will have to install or compile gcc-arm [1] and FirmwareSender [2] from source.

[1] https://launchpad.net/gcc-arm-embedded
[2] https://github.com/pingdynasty/FirmwareSender

**Comment by samuele-artuso** [comment]
Setting up a 32 bit machine is not a problem.

How would all this work from the user stanpoint? What is the workflow?

**Comment by samuele-artuso** [comment]
I guess there will be a button saying "compile patch". When clicked it will sort of "enqueue" a job somewhere that can be checked for progress or completion, and at the end the user will be able to examine the output of the build and download the binary onto his/her machine?

**Comment by samuele-artuso** [comment]
I'm having problems running a virtual machine on the server. I tried with both VirtualBox and KVM, but I couldn't get them to work. I suspect that Gandi disabled virtualization support.

This means that we need to do the build in a 64-bit envo and without a virtual machine, until we fix the problem (if ever).

I tried to install gcc-arm but it seems really difficult. Can you give it a shot? I think it will take me a lot of time to figure it out myself.

Apart from this, the build process works a treat on my own computer.

**Comment by pingdynasty** [comment]
I could try asking on the gandi forum but they'll probably tell me to pay
for another server.

Not sure if this [1] is any help, probably a red herring (I've no idea
what Dedibox is).

There should be a debian package for the gcc-arm toolchain, but it's not
showing up on nestor. See [2], or try to use this PPA [3] (though it's for
Debian so could be a bad idea).

[1]
https://forums.virtualbox.org/viewtopic.php?f=1&t=45444&p=204920&hilit=gandi#p204920
[2] https://packages.debian.org/sid/devel/gcc-arm-none-eabi
[3] https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded

**Comment by pingdynasty** [comment]
building from source now on nestor - so far so good.

**Comment by pingdynasty** [comment]
I've got it working by installing the required i386 libs:
```
dpkg --add-architecture i386
apt-get update
apt-get install ia32-libs
```

I can now compile from ~mars/OwlWare.online/ with
```make BUILD=/tmp/foo ONLINE_INCLUDES='#include \"PhaserPatch.hpp\"'
ONLINE_REGISTER='REGISTER_PATCH(PhaserPatch, \"Phaser\", 2, 2);' online```

**Comment by pingdynasty** [comment]
I've got it working by installing the required i386 libs:
```
dpkg --add-architecture i386
apt-get update
apt-get install ia32-libs
```
I can now compile from ~mars/OwlWare.online/ with
`make BUILD=/tmp/foo ONLINE_INCLUDES='#include \"PhaserPatch.hpp\"'
ONLINE_REGISTER='REGISTER_PATCH(PhaserPatch, \"Phaser\", 2, 2);' online`

(no markdown in edit mode? weird!)

**Comment by pingdynasty** [comment]
> I guess there will be a button saying "compile patch".

Yes, but only on the user's own patches.

> When clicked it will sort of "enqueue" a job somewhere that can be checked for progress or completion

It would be fine I think to have the request on hold while compilation is happening, it shouldn't take more than a few secs. (compiling Phaser or FreeVerb on nestor takes 3-4 secs).
Queueing would be nice but sounds like a lot more work.
If it is synchronous it should be easier to display error/success messages.

> at the end the user will be able to examine the output of the build and download the binary onto his/her machine?

Yes the download link should be available on the public patch details page.

**Comment by samuele-artuso** [comment]
> Yes the download link should be available on the public patch details page.
Available for anyone to download? or the the owner only? and for how long?

I was thinking that I may not be able to catch any error condition. Maybe I should abort the compilation if it takes too long? What a sensible time-out would be?

**Comment by pingdynasty** [comment]
20 or 30 secs timeout is fine.

The patch details should have an (optional) field for sysex file. It
should be viewable (if present) by anyone, so public.
There's only ever one sysex per patch,, so a new compilation replaces a
previous sysex. It doesn't expire.
If the compilation fails, the existing sysex is not replaced.

I'll add an issue to display the sysex and compilation date in the Patch
Details page.

We might want to add a 'remove sysex' button to the Patch Edit page, but
not necessary yet.

**Comment by pingdynasty** [comment]
The local build of arm-gcc failed - ran out of space after using up 6.3Gb!
Better anyhow to use the official 32bit build as we can upgrade more easily.

**Comment by samuele-artuso** [comment]
What is the syntax for compiling patches that have more than one source file?

**Comment by pingdynasty** [comment]
This question brings up a couple of issues I hadn't quite anticipated.
The easy way is to simply copy all files to the temp build directory and hash-include the first one. An example is ResonantFilterPatch.hpp which depends on SampleBasedPatch.hpp
```
make BUILD=/tmp/bar ONLINE_INCLUDES='#include \"ResonantFilterPatch.hpp\"\n' ONLINE_REGISTER='REGISTER_PATCH(ResonantFilterPatch, \"Resonant Filter\", 2, 2);' online
```
Question 1) how do you know which is the 'main' file, the one to add to ONLINE_INCLUDES
Question 2) (relevant also to single file patches) how do you know the patch class name

**Comment by samuele-artuso** [comment]
The patch class name is the first argument to `REGISTER_PATCH()`, isn't it?

**Comment by samuele-artuso** [comment]
Naïve way:

    egrep ^class SomePatch.hpp | cut -d' ' -f2

Or we could go for the Java-esque convention of naming the class after the file?

About question (1), we could require that the first file in the edit patch form be the main one. I _think_ that the order will preserved in the database, but I'd rather double-check.

A more involved solution is to add a radio button for the user to indicate the main source file, but it could take me much more time.

**Comment by pingdynasty** [comment]
A c++ file can define many classes...
Let's do this: the filename must be ClassName.hpp, as in all our current patches.
And patch file must be the first one.
All other files will be simply copied to the build directory.

**Comment by samuele-artuso** [comment]
OK.

> A c++ file can define many classes...

Otherwise it would feel to easy :P

**Comment by samuele-artuso** [comment]
Can I trust the exit status of `make` to determine if the compilation succeeded? `0` = successful and anything else = failure?

**Comment by pingdynasty** [comment]
Let's make it so - if you don't get the right status let me know and
I'll fix the makefile

**Comment by samuele-artuso** [comment]
This is now complete.

You can find a "Compile" link on the left, under the patch parameters:

![patch3](https://cloud.githubusercontent.com/assets/3853889/6909247/00a4ed6e-d73c-11e4-8150-324426447546.png)

In order to see the "Compile" link you need to be either an admin or the author of the patch itself. If the patch doesn't have any source files, the link won't be available.

Regardless of whether the compilation succeeds or not, `stdout` and `stderr` of the `make` command will be available for inspection, as per the image below:

![patch2](https://cloud.githubusercontent.com/assets/3853889/6909277/5fc4c13e-d73c-11e4-8caa-b6dca8ce5d64.png)

The removal of SysEx files is not yet supported in the UI. You can delete a patch anyway deleting its `.syx` file in `/var/www/hoxtonowl.com/subdomains/www/patch-builder/build`.

I hope this comes on time for your presentation. I tested it at my best, but should you find any bugs let me know and I'll try to fix them as soon as I can.

Please mind that the compilation process downloads the source code for each patch from GitHub every time. There is no caching of the source files at the moment. GitHub has had availability problems over the last 4 days, so check GitHub is working before blaming me:P

Unfortunately I'm not available tomorrow (flying to Italy), but I will regularly be regulary available from Wednesday (included) on.

**Comment by GuillaumeLeNost** [comment]
Great job ! Just tested on JotReverb, works well !
Thanks !

**Comment by pingdynasty** [comment]
I've updated OwlProgram.online on staging so that it uses the latest version.
It doesn't yet build for web, need to install emscripten for that.

**Comment by pingdynasty** [comment]
closing this as done.
