### ISSUE TITLE
Show sysex download link in Patch Details

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#67]
If the patch has a sysex file associated with it, it should show in the Patch Details page.
I think it should show either in the patch-stats2 div, or beneath the parameters in its own box, whichever looks and works best.

The link should say:
 'Download SysEx'  - Last updated 1/2 2034

**Comment by samuele-artuso** [comment]
Am I free to rename the `.syx` file any way I want? e.g. `PatchName.syx`

**Comment by pingdynasty** [comment]
yes, please do. PatchName.syx is good.

**Comment by samuele-artuso** [comment]
I placed it under the instructions.

![shot](https://cloud.githubusercontent.com/assets/3853889/6886353/4178ae44-d632-11e4-84e7-efd33067c0ca.png)

**Comment by GuillaumeLeNost** [comment]
Great, seen it on the Compressor Patch page.
Is there a « Compile » button already in place ?

**Comment by samuele-artuso** [comment]
On 29 Mar 2015 18:28, "GuillaumeLeNost" <notifications@github.com> wrote:
> Is there a « Compile » button already in place ?

ETA is tomorrow afternoon.
