### ISSUE TITLE
Identify suitable patch editor

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#7]
We need a patch editor that must:
- run in the browser
- be open source
- have syntax highlighting (of C/C++ at least, preferably extensible to Faust)

and should ideally:
- be mobile / tablet friendly
- be under active development
- be implemented in modern JS / HTML5
- play nice with git / github / gist

**Comment by samuele-artuso** [comment]
do you still need me to set up an instance on the staging server or shall we put this off until later?

**Comment by goozo** [comment]
I believe this is resolved.
