### ISSUE TITLE
Integrate OwlProgram docs

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#73]
The OwlProgram repository has a 'docs' target which builds doxygen documentation for the library classes.
This documentation should be published and linked to on the website. A link from the wiki would be fine.
There is a doxygen extension for mediawiki [1] but it seems very out of date.

The generated docs currently look like this [2] but the doxygen configuration can easily be changed.

[1] https://www.mediawiki.org/wiki/Extension:DoxyWiki
[2] http://bella.pingdynasty.com/~mars/OWL/docs/html/

**Comment by samuele-artuso** [comment]
I don't fully understand this, I'm afraid. Patches don't contain docblocks, so I guess that `make docs` generates the documentation for the OwlProgram project? Do I have to write a script that runs `make docs`? Could you show me an example of `make docs`?

**Comment by marsus** [comment]
It's much simpler than that.
The docs are for the library and API, and will be static. We just need to generate them whenever there's a new release.
If you could create a directory to host them from, then I'll add a link to it from the wiki.

**Comment by samuele-artuso** [comment]
Got it. Do you need me to update Doxygen's template to make it match the website?

**Comment by marsus** [comment]
Would be great if you could

**Comment by samuele-artuso** [comment]
Here come the docs: http://www.hoxtonowl.com/docs/index.html

`hoxtonowl.com/docs` is a symlink to `/opt/OwlProgram.online/Build/docs/html`.

**Comment by marsus** [comment]
cool - I've linked it from the wiki

**Comment by pingdynasty** [comment]
closing this
