### ISSUE TITLE
Update online compiler invocation

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#74]
The online compiler currently runs `make` with some fairly complex arguments.

The make file has been updated to accept more specific options (env vars):
* PATCHNAME: specify name of patch, e.g. SimpleDelay
* PATCHCLASS: name of patch class, e.g. SimpleDelayPatch
* PATCHFILE: name of main patch file, e.g. SimpleDelayPatch.hpp
* PATCHIN: number of input channels, default 2
* PATCHOUT: number of output channels, default 2

(see readme in https://github.com/pingdynasty/OwlProgram)

The old target `make online` is still supported, with the old options, but better to run `make sysex` with the new set of options.

**Comment by samuele-artuso** [comment]
Just so I'm sure I got this right, do you need me to update the patch compilation process so that it uses `make sysex` instead of [`make online`](https://github.com/pingdynasty/OwlServer/issues/66#issuecomment-85998573)?

**Comment by pingdynasty** [comment]
yes pls

On 08/07/15 18:58, Sam Artuso wrote:
>
> Just so I'm sure I got this right, do you need me to update the patch
> compilation process so that it uses |make sysex| instead of |make
> online|
> <https://github.com/pingdynasty/OwlServer/issues/66#issuecomment-85998573>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingdynasty/OwlServer/issues/74#issuecomment-119678776>.
>

-- 
Martin Klang
Alpha Plus Technology Ltd
London UK

**Comment by marsus** [comment]
Additional options that are relevant to online build, I think these are the same as before:
* BUILD: output directory for temporary files (default: `./Build/`)
* PATCHSOURCE: where the patch files are (default: `./PatchSource/`)

It should be possible to build without copying the OwlProgram folder, simply create a temporary source directory `PATCHSOURCE` to put the user files in, and a temporary target directory `BUILD`, and invoke the makefile with the right options.

**Comment by samuele-artuso** [comment]
This should be fixed now.

I tested a few patches and all those that build with `make online` also build with `make sysx`.

I've noticed that many patches won't build at all with either method, e.g. Simple Delay or FreeVerb. There seem to be missing files (`CircularBuffer.hpp` in the case of Simple Delay and `ReverbHeader.h` in the case of FreeVerb). Were you aware of this?

**Comment by pingdynasty** [comment]
Yes they're missing dependencies, need to add the github files.

http://hoxtonowl.com/patch-library/patch/Simple_Delay/
Works now.

**Comment by samuele-artuso** [comment]
OK, just wanted to make sure this wansn't a bug at my end. Closing this issue.
