### ISSUE TITLE
Check logs and stats on nestor

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#76]
There's some pretty big logfiles on nestor
```
ls -lh /var/www/hoxtonowl.com/subdomains/www/logs/
total 294M
-rw-rw-r-- 1 www-data www-data 153M Jul  7 18:57 access.log
-rw-rw-r-- 1 www-data www-data 141M Jul  7 18:57 error.log
```
@samuele-artuso : maybe the verbosity level is too high? Also, are the logs rotated? Thirdly, we had awstats on the old server (buenaventura), what stats do we have on nestor?

**Comment by samuele-artuso** [comment]
* Lowered verbosity level of Apache from `debug` to `warn` (recommended by documentation for production systems);
* Configured and enable `logrotate` (the configuration is in `/etc/logrotate.d/owl-website`);
* Installed popular open-source [Piwik](http://piwik.org/) stats package;
    * I disabled first-party tracking cookies—this will give us less data but is more privacy-friendly for our users;
    * made you an administrator and emailed you the access credentials.

**Comment by pingdynasty** [comment]
works!
