### ISSUE TITLE
Render PD patches

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#78]
Patches come in three flavours: C++, FAUST and PD (Pure Data).

PD patches should be rendered using either this service [1] or this [2] utility.

Here [3] is an example PD patch.

[1] http://forum.pdpatchrepo.info/topic/9002/open-source-web-service-to-render-pd-patches-to-svg
[2] https://www.npmjs.com/package/pd-fileutils
[3] http://hoxtonowl.com/patch-library/patch/HeavyOWL/

**Comment by samuele-artuso** [comment]
Can PD patches be made of more than 1 file? if so, shall I just concatenate all the files together and pass the result to the renderer?

**Comment by pingdynasty** [comment]
Yes they can, but render each file in a tab as with C++ files.
I think it will be possible to mix and match different file types as
well, so a tab for each file is good.

btw compilation with multiple files works great!

**Comment by pingdynasty** [comment]
To clarify: the renderer is to be used instead of the syntax highlighter
for PD files. No need to show text version.

**Comment by samuele-artuso** [comment]
This is now in the staging environment.

**Comment by pingdynasty** [comment]
ok so I tried adding a PD file to this patch
http://staging.hoxtonowl.com/patch-library/patch/another_test_patch/

I'd like to see the rendered PD diagram in Patch Code: HeavyOwl.pd
_instead_of_ the text content of the file. If that's do-able. That way
we don't need the 'Render PD patch' button.

PD patches are distinguished by the suffix `.pd`, so if a file ends in
.pd it should be rendered this way.

**Comment by pingdynasty** [comment]
While you're at it, could you pls link the file name (tab title) to its github source file, #70

**Comment by samuele-artuso** [comment]
On staging. Tested with multiple PD patches and with mix & match scenario.

**Comment by pingdynasty** [comment]
awesome, looks great!

**Comment by GuillaumeLeNost** [comment]
looks cool ! do i need to be logged in on heavy to compile a patch like
this one ?
http://staging.hoxtonowl.com/patch-library/patch/another_test_patch/

2015-07-20 19:57 GMT+01:00 Martin Klang <notifications@github.com>:

**Comment by samuele-artuso** [comment]
You always need to be logged in to compile patches, and either be the patch's author or a website administor (which you are).

**Comment by tamagazzi** [comment]
Nice work - looks great! The text file is also useful, though, as you can copy/paste text directly into Pd, which then creates the patch diagram for you to edit graphically.

**Comment by samuele-artuso** [comment]
@tamagazzi: to get the source code, you can just click on the "Open this file in GitHub" in the right corner.

**Comment by pingdynasty** [comment]
can we push this to nestor and close the issue pls?
