### ISSUE TITLE
Tags missing on patch details page

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#82]
If the screen resolution is low (<1200) then the tags are not displayed with the patch details.

**Comment by pingdynasty** [comment]
screengrab without tags (medium screen size)
![grab](https://cloud.githubusercontent.com/assets/648870/10483428/5ba22e58-7277-11e5-9787-0d11a233bfb6.png)

with tags (small screen size)
![grab](https://cloud.githubusercontent.com/assets/648870/10483498/b4912424-7277-11e5-8cb2-0e574f105ac7.png)

**Comment by jayrope** [comment]
Happens here as well. In more detail tagging works here during initial creating of patch üage and patch upload. Later on, when editing, they disappear and have to be reinserted every time.

**Comment by pingdynasty** [comment]
done and deployed
