### ISSUE TITLE
Wrong url in patch library

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#83]
The url should be updated when clicking 'Browse all', 'Latest', 'Tags', 'Authors', or 'My patches', instead of remaining on the last clicked patch.
To reproduce, click PATCHES, then Bitta patch, then Browse All. The URL remains `http://hoxtonowl.com/patch-library/patch/Bitta/`

**Comment by pingdynasty** [comment]
Also: on the patch details page, e.g.
http://hoxtonowl.com/patch-library/patch/OL_DroneBox/
the page title should is currently `The OWL | Patches`. I think it should be `The OWL | Name of patch`.

**Comment by goozo** [comment]
URL is fixed, should the Page Title Issue be addressed now?
