### ISSUE TITLE
Piwik broken?

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#86]
The piwik link was throwing up an error for directory not writeable
http://hoxtonowl.com/piwik/
I changed the group from hoxtonowl to www-data:
`sudo chgrp -R www-data /var/www/hoxtonowl.com/subdomains/www/httpdocs/piwik/tmp/`
Now the page loads, but is showing 0 visits since 6 Aug.

**Comment by samuele-artuso** [comment]
Fixed.
