### ISSUE TITLE
Make some patch details optional (for private patches)

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#87]
The patch form has many required fields, which makes sense for publishing a patch but not for a private patch that is work in progress.
If possible (easy) I'd like some fields to be mandatory only for published patches:
CPU, Memory, Instructions.
If not easy, make these optional for all patches.

**Comment by samuele-artuso** [comment]
Fixed.

**Comment by pingdynasty** [comment]
`Instructions` still mandatory, pls make it optional

**Comment by samuele-artuso** [comment]
Could you double-check? In my tests, it works as expected.

That field is mandatory if the patch is public:

![instructions-1](https://cloud.githubusercontent.com/assets/3853889/9822423/42407434-58b8-11e5-9297-b893e75cb24b.png)

...but it becomes optional as soon as you mark the patch as private (and the * symboly that denotes mandatory fields will disappear accordingly):

![instructions-2](https://cloud.githubusercontent.com/assets/3853889/9822436/5fa74bba-58b8-11e5-8f1f-6646db2b3f3a.png)

An empty instructions field will be accepted if the patch is private, but it will error out if the patch is public. If you believe there's some bug I haven't spotted, please let me know how to reproduce it.

**Comment by samuele-artuso** [comment]
Are you happy to close this one?

**Comment by pingdynasty** [comment]
yes, tested working

**Comment by pingdynasty** [comment]
CPU and Memory are still showing as required, see screenshot (private patch):
![selection_001](https://cloud.githubusercontent.com/assets/648870/10794934/3690f978-7d8f-11e5-9717-a65dd8ef8d8c.png)
