### ISSUE TITLE
Show Latest Patches by default

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#88]
The patch library should by default show Latest, instead of Browse all
http://staging.hoxtonowl.com/patch-library/
The text on Browse All should be changed to All, and the icon should be moved to last position, i.e. to the right of Authors.

**Comment by samuele-artuso** [comment]
I've placed it to the right of "Authors" but still to the left of "My patches" (which shows up only if you're logged in).

**Comment by pingdynasty** [comment]
perfect - closing.
