### ISSUE TITLE
Patch source file upload

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#90]
We'd like for users to be able to compile patches without using github. This is the purpose of #69, but that is quite a complex task.

First, we should add a file upload facility to the patch edit page.
I'd like it to be in a box between 'Soundcloud samples' and 'GitHub files', and look similar to the latter.
Each uploaded file will have an editable name and a 'remove' button.
Uploading a file will store it in the db, but we don't need to support version tracking or anything.

An uploaded file should be copied to the build/source directory same as a github file when the patch is compiled. It should be displayed in the same way as a github file (syntax highlight or PD rendered), but obviously without the github link.

If the user is the owner of the patch, they should be able (from the patch details page) to click an 'Update' link which lets them upload a new version.

Once this is working, we can add an 'Edit' link which would bring up the in-browser editor, but that will be a separate task.

**Comment by samuele-artuso** [comment]
1. At the moment, the "main" source file is the first GitHub file. How do you suggest to determine which file is the main file?
2. I guess that pick-and-mix between GH and manually uploaded files is going to be possible?

**Comment by pingdynasty** [comment]
2. yes

1. good question.
If there's both types, the uploaded (locally stored) takes precedence, so first local file if there is one, otherwise first github.

At some point we'll probably have to make the classname and main filename configurable from the patch details, but good defaults are fine for now.

**Comment by samuele-artuso** [comment]
Idea! :bulb: 

I suggest to replace the GitHub box with the box below:
![mockup](https://cloud.githubusercontent.com/assets/3853889/9798034/69796e24-57f6-11e5-9fe9-7accbfc47003.png)

GitHub and manually uploaded files would be mixed together. The first file would still be the main file. 

I suggest that when the "Upload file" button is used, the file gets uploaded on the filesystem of the server and its public URL added as a new _textedit_ widget. This would make up for simpler code.

**Comment by pingdynasty** [comment]
ok good -
what happens when the uploaded file is updated with a new version, does the url stay the same?
Since several patches can use the same filename the url must have a unique path, perhaps the uid of the patch as directory?

**Comment by pingdynasty** [comment]
I like it, much better this way :+1: 

Let's add a comment, e.g.
'Upload a file [Browse...] or paste a URL from GitHub'.

It also seems to me that if there's a directory on the server with uploaded files for the patch, then this could also be used as the source directory for compilations - just need to copy any GitHub files into it and go. No?

**Comment by samuele-artuso** [comment]
> what happens when the uploaded file is updated with a new version, does the url stay the same?

Yes. If I don't go wrong, the original name of the file on the user's machine is provided in a HTTP header, so I'll use that. So, if the user is uploading a file whose name is already in the database, I'll overwrite it. Makes sense?

> Since several patches can use the same filename the url must have a unique path, perhaps the uid of the patch as directory?

Patch names are already guaranteed to be unique, so we could have something like: `http://www.hoxtonowl/files/PatchName/FileName.hpp`

**Comment by samuele-artuso** [comment]
> 'Upload a file [Browse...] or paste a URL from GitHub'.

As a side note, it would also be easy to allow source files to be hosted _anywhere_, GitHub being a special case (because we are accepting URLs of the source file displayed à-la-GitHub, i.e. [this](https://github.com/pingdynasty/OwlPatches/blob/master/CircularBuffer.hpp) instead of [this](https://raw.githubusercontent.com/pingdynasty/OwlPatches/master/CircularBuffer.hpp)). I'll leave this for later though.

**Comment by samuele-artuso** [comment]
> It also seems to me that if there's a directory on the server with uploaded files for the patch, then this could also be used as the source directory for compilations - just need to copy any GitHub files into it and go. No?

Yes, it could be used as source directory, but it will be publicly exposed on the intertubes. I think it's best to stick to the temporary directory I'm using inside `/tmp`.

**Comment by pingdynasty** [comment]
>  So, if the user is uploading a file whose name is already in the database, I'll overwrite it. 

yes

> Patch names are already guaranteed to be unique, so we could have something like: http://www.hoxtonowl/files/PatchName/FileName.hpp

yes, all good!

> I think it's best to stick to the temporary directory I'm using inside /tmp.

ok

**Comment by samuele-artuso** [comment]
Could you give me a complete list of file types/extensions that can be uploaded? I would say `.hpp`, `.cpp`, `.pd` and `.dsp`. Can you confirm?

What do you suggest as maximum allowed file size for uploads?

**Comment by pingdynasty** [comment]
add .c, .h and .s

**Comment by pingdynasty** [comment]
max file size 256kB

**Comment by samuele-artuso** [comment]
On staging server. Feedback is very welcome!

**Comment by pingdynasty** [comment]
Works great, compilation too. Pls roll out as it is to the live server.

A couple of things to improve:
* The File input field shows the webserver URL, which shouldn't really be user editable.
It would be great if it just shows the file name and Remove button.
* On the Patch Details page, if the user owns the patch I'd like there to be an 'Update file' link, right where the 'View on GitHub' link is. 'Update file' allows the user to replace the file.

The process is this:
- user creates a new patch with the first version of a source file
- compiles and downloads sysex
- updates file, recompiles, downloads (repeat)

For the last step we don't want to have to go back to the Edit page.

**Comment by samuele-artuso** [comment]
OK. Published it on live server as it is, for now.

**Comment by pingdynasty** [comment]
Someone has reported file upload not working (on live)
http://hoxtonowl.com/forums/topic/compiling-pure-data-patches-to-run-on-owl/

I can confirm this is the case, after Choose Files... the file field is still empty.
Also the CPU cycles field is required (private patch) which it shouldn't be.

![grab](https://cloud.githubusercontent.com/assets/648870/10482907/e1cbbc0a-7273-11e5-97ca-9440c4bdf02e.png)

**Comment by samuele-artuso** [comment]
Cannot reproduce.

I created a new patch, set it as private and uploaded this file https://github.com/pingdynasty/OwlPatches/blob/master/TremoloPatch.hpp:
* The file field wasn't empty; and
* the CPU cycles field wasn't marked as required.

I was then able to build and download the patch normally.

What are the exact steps to reproduce this?

**Comment by pingdynasty** [comment]
done.
