### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#93]
New tags needed in patch library:
* PD
* C++
* Arpeggiator
* Envelope
* LFO
* Oscillator

**Comment by samuele-artuso** [comment]
I made it possible to add new tags when creating/editing patches. In staging for now. Let me know if you're happy and I'll push it live.

**Comment by pingdynasty** [comment]
Can you make it admin only for creating new tags?
There's a weird entry at the bottom of the list of tags, says `[object Object]`.
Sorry, having problems doing a screengrab atm...
If it's admin only, the [object Object] thing is not a problem.
